language: julia

os: - linux
  - osx

compiler:
  - clang

julia:
  - 0.3
  - 0.4
  - nightly

notifications:
  email:
    recipients:
      - andreasnoackjensen@gmail.com
    on_success: never

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("RNGTest"); Pkg.test("RNGTest", coverage=true)'
